# FROM python:3.9-slim-buster
FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api_data_fetcher_kafka.py .

CMD ["python", "api_data_fetcher_kafka.py"]


