name: Build and Deploy to Server
on:
  push:
    branches:
      - Production

permissions:
  contents: read
  packages: write 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST }}
          username:  ${{secrets.SERVER_USERNAME }}
          password: ${{secrets.SERVER_PASSWORD }}
          script: |
            cd /home/job/imarika_data_pipeline/imarika-weather-pipeline || exit 1
            git pull origin Production 
            chmod +x start-pipeline.sh  
            ./start-pipeline.sh deployment 
            echo "Deployment completed successfully."